base_dir: /home/anna.jungbluth/outputs/msg-to-goes/
data:
  A_path: /mnt/disks/msg-data/msg/
  # converted_A_path:
  B_path: /mnt/disks/goes-data/goes/
  # converted_B_path: 
  num_workers: 4
  iterations_per_epoch: 1000
  patch_size: (256, 256)
model:
  input_dim_a: 11
  input_dim_b: 16
  upsampling: 0
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: 'none' # 'in_rs_aff'
  use_batch_statistic: False
logging:
  wandb_entity: itieo
  wandb_project: msg-to-goes
  wandb_name: msg-to-goes-all-channels
training:
  epochs: 100
normalization: # TODO: Change to avoid absolute paths
  A_norm_dir: /home/anna.jungbluth/InstrumentToInstrument/dataset/msg_2020_hourly.csv
  B_norm_dir: /home/anna.jungbluth/InstrumentToInstrument/dataset/goes_2020_hourly.csv