base_dir: /home/anna.jungbluth/outputs/msg-to-goes/
data:
  A_path: /mnt/disks/pretraining/2025-esl-3dclouds-extremes-datasets/pre-training/msg
  converted_A_path: /home/anna.jungbluth/tmp-data/msg/
  B_path: /mnt/disks/pretraining/2025-esl-3dclouds-extremes-datasets/pre-training/goes
  converted_B_path: /home/anna.jungbluth/tmp-data/goes/
  num_workers: 4
  iterations_per_epoch: 10
  # NOTE: Our patches are now already 1024 x 1024
  A_patch_size: (1024, 1024) # Larger patches are saved for accelerated training.
  B_patch_size: (1024, 1024) # Patches are further cropped to (256, 256) before training.
  A_bands: [
            # 640.0,
            # 810.0,
            # 1640.0,
            # 3920.0,
            # 6250.0,
            # 7350.0,
            # 8700.0,
            # 9660.0,
            # 10800.0,
            # 12000.0,
            13400.0,
        ]
  B_bands: [
          # 470.0,
          # 640.0,
          # 870.0,
          # 1380.0,
          # 1610.0,
          # 2250.0,
          # 3890.0,
          # 6170.0,
          # 6930.0,
          # 7340.0,
          # 8440.0,
          # 9610.0,
          # 10330.0,
          # 11190.0,
          # 12270.0,
          13270.0,
      ]
model:
  input_dim_a: 1
  input_dim_b: 1
  upsampling: 0
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: 'in_rs_aff'
  use_batch_statistic: False
  # Set the identity loss to 0
  # lambda_reconstruction_id: 0
  # lambda_content_id: 0
logging:
  wandb_entity: itieo
  wandb_project: msg-to-goes
  wandb_name: # MSG_to_GOES-infrared-5bands (8.7 - 13.4 um) [no identity loss]
training:
  epochs: 200
  limit_train_batches: null
  limit_val_batches: null
