base_dir: /home/anna.jungbluth/outputs/msg-to-goes/
data:
  A_path: /home/data/msg/
  converted_A_path: /home/anna.jungbluth/tmp-data/msg/
  B_path: /home/data/goes/
  converted_B_path: /home/anna.jungbluth/tmp-data/goes/
  num_workers: 4
  iterations_per_epoch: 1000
  A_patch_size: (1024, 1024) # Larger patches are saved for accelerated training.
  B_patch_size: (1024, 1024) # Patches are further cropped to (256, 256) before training.
  A_bands: [0.64, 0.81, 1.64, 3.92, 6.25, 7.35, 8.7, 9.66, 10.8, 12.0, 13.4]
  B_bands: [0.47, 0.64, 0.87, 1.38, 1.61, 2.25, 3.89, 6.17, 6.93, 7.34, 8.44, 9.61, 10.33, 11.19, 12.27, 13.27]
model:
  input_dim_a: 11 
  input_dim_b: 16
  upsampling: 0
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: 'in_rs_aff'
  use_batch_statistic: False
logging:
  wandb_entity: itieo
  wandb_project: msg-to-goes
  wandb_name: MSG_to_GOES-infrared-11bands (6.25 - 13.4 um)
training:
  epochs: 200
  limit_train_batches: null
  limit_val_batches: null
normalization:
  A_norm_dir: /home/anna.jungbluth/InstrumentToInstrument/dataset/msg_2020_hourly_subset.csv
  B_norm_dir: /home/anna.jungbluth/InstrumentToInstrument/dataset/goes_2020_hourly_subset.csv
