data:
  load_from_numpy: True # If True, we don't need the converted_path or patch_sizes
  B_satellite: msg
  B_path: /mnt/disks/data/iti-converted/msg
  B_bands: [
            640.0,
            810.0,
            1640.0,
            3920.0,
            6250.0,
            7350.0,
            8700.0,
            9660.0,
            10800.0,
            12000.0,
            13400.0,
        ]

  A_satellite: himawari
  A_path: /mnt/disks/data/iti-converted/himawari-3000m
  A_bands: [
            470.0,
            510.0,
            640.0,
            860.0,
            1600.0,
            2300.0,
            3900.0,
            6200.0,
            6900.0,
            7300.0,
            8600.0,
            9600.0,
            10400.0,
            11200.0,
            12400.0,
            13300.0,
        ]
  filter_daytime: False
  stats_filepath: /data/2025-esl-3dclouds-extremes-datasets/pre-training-reprocessed/pretrain_stats.csv
model:
  input_dim_a: 1
  input_dim_b: 1
  upsampling: 0
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: 'in_rs_aff'
  use_batch_statistic: False
  # Set the identity loss to 0
  # lambda_reconstruction_id: 0
  # lambda_content_id: 0
logging:
  wandb_entity: itieo
  wandb_project: HIMAWARI8-to-MSG
  wandb_name: HIMAWARI8-MSG-X
  tags: [msg, himawari8]
training:
  epochs: 100
  limit_train_batches: null
  limit_val_batches: 0.5
  num_workers: 8
  iterations_per_epoch: 1000
seed: 42
