data:
  A_satellite: himawari
  A_path: /mnt/disks/pretraining/2025-esl-3dclouds-extremes-datasets/pre-training/himawari/l1b
  A_patch_size: (256, 256) # Larger patches for storage.
  converted_A_path: /home/anna.jungbluth/tmp-data/himawari
  converted_A_patch_size: (256, 256) # Smaller patches for training.
  # A_resolution: null # If null, native resolution of the satellite is used.
  # A_center_crop: False # Crop always around the center with given radius.
  # A_radius: 0
  A_bands: [
        # 470.0,
        # 510.0,
        # 640.0,
        # 860.0,
        # 1600.0,
        # 2300.0,
        # 3900.0,
        # 6200.0,
        # 6900.0,
        # 7300.0,
        # 8600.0,
        # 9600.0,
        # 10400.0,
        # 11200.0,
        12400.0,
        # 13300.0,
      ]

  B_satellite: goes
  B_path: /mnt/disks/pretraining/2025-esl-3dclouds-extremes-datasets/pre-training/goes/mcmip
  B_patch_size: (256, 256) # Larger patches for storage.
  converted_B_path: /home/anna.jungbluth/tmp-data/goes
  converted_B_patch_size: (256, 256) # Smaller patches for training.
  # B_resolution: null # If null, native resolution of the satellite is used.
  # B_center_crop: False # Crop always around the center with given radius.
  # B_radius: 0
  B_bands: [
          # 470.0, # VIS
          # 640.0, # VIS
          # 870.0, # NIR
          # 1380.0, # NIR
          # 1610.0, # NIR
          # 2250.0, # NIR
          # 3890.0, # IR (with relflected daytime component)
          # 6170.0, # IR
          # 6930.0, # IR
          # 7340.0, # IR
          # 8440.0, # IR
          # 9610.0, # IR
          # 10330.0, # IR
          # 11190.0, # IR
          12270.0, # IR
          # 13270.0, # IR
      ]

model:
  input_dim_a: 1
  input_dim_b: 1
  upsampling: 0
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: 'in_rs_aff'
  use_batch_statistic: False
  # Set the identity loss to 0
  # lambda_reconstruction_id: 0
  # lambda_content_id: 0
logging:
  wandb_entity: itieo
  wandb_project: HIMAWARI8-to-GOES16
  wandb_name: HIM8-GOES16-1ch-[12.4um]
  tags: [himawari8, goes16]
training:
  epochs: 100
  limit_train_batches: null
  limit_val_batches: 0.5
  num_workers: 6
  iterations_per_epoch: 1000
